name: pr-generation-from-ticket
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - jira==3.5.0
    - PyGithub==1.59.1
    - google-generativeai==0.3.2
    - tiktoken
    - requests>=2.31.0